% Definition of parameter


ka = zeros(266,1);
ka(1) = 1;         % 1a: in 1/min ERMemAA -----> CytAA (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 1b: in 1/min GolgiMemAA -----> CytAA (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(2) = 100;       % 2a: in 1/min CytAA -----> ERMemAA (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 2b: in 1/min CytAA -----> GolgiMemAA (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(3) = 1;         % 3a: in 1/min ERMem11-HPETE -----> Cyt11-HPETE (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 3b: in 1/min GolgiMem11-HPETE -----> Cyt11-HPETE (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(4) = 100;       % 4a: in 1/min Cyt11-HPETE -----> ERMem11-HPETE (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 4b: in 1/min Cyt11-HPETE -----> GolgiMem11-HPETE (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(5) = 1;         % 5a: in 1/min ERMem5-HPETE -----> Cyt5-HPETE (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 5b: in 1/min GolgiMem5-HPETE -----> Cyt5-HPETE (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(6) = 100;       % 6a: in 1/min Cyt5-HPETE -----> ERMem5-HPETE (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 6b: in 1/min Cyt5-HPETE -----> GolgiMem5-HPETE (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(7) = 1;         % 7a: in 1/min ERMemPGE2 -----> CytPGE2 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 7b: in 1/min GolgiMemPGE2 -----> CytPGE2 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(8) = 1;         % 8a: in 1/min CytPGE2 -----> ERMemPGE2 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 8b: in 1/min CytPGE2 -----> GolgiMemPGE2 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(9) = 1;         % 9a: in 1/min ERMemPGA2 -----> CytPGA2 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 9b: in 1/min GolgiMemPGA2 -----> CytPGA2 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(10) = 1;        % 10a: in 1/min CytPGA2 -----> ERMemPGA2 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 10b: in 1/min CytPGA2 -----> GolgiMemPGA2 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(11) = 1;        % 11a: in 1/min ERMemPGD2 -----> CytPGD2 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 11b: in 1/min GolgiMemPGD2 -----> CytPGD2 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(12) = 1;        % 12a: in 1/min CytPGD2 -----> ERMemPGD2 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 12b: in 1/min CytPGD2 -----> GolgiMemPGD2 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(15) = 1;        % 15a: in 1/min ERMemPGJ2 -----> CytPGJ2 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 15b: in 1/min GolgiMemPGJ2 -----> CytPGJ2 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(16) = 1;        % 16a: in 1/min CytPGJ2 -----> ERMemPGJ2 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 16b: in 1/min CytPGJ2 -----> GolgiMemPGJ2 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(17) = 1;        % 17a: in 1/min ERMemLTC4 -----> CytLTC4 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 17b: in 1/min GolgiMemLTC4 -----> CytLTC4 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(18) = 1;        % 18a: in 1/min CytLTC4 -----> ERMemLTC4 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 18b: in 1/min CytLTC4 -----> GolgiMemLTC4 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(19) = 1;        % 19a: in 1/min ERMem5-HETE -----> Cyt5-HETE (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 19b: in 1/min GolgiMem5-HETE -----> Cyt5-HETE (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(20) = 1;        % 20a: in 1/min Cyt5-HETE -----> ERMem5-HETE (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 20b: in 1/min Cyt5-HETE -----> GolgiMem5-HETE (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(21) = 1;        % 21a: in 1/min ERMem15-HETE -----> Cyt15-HETE (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 21b: in 1/min GolgiMem15-HETE -----> Cyt15-HETE (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(22) = 1;        % 22a: in 1/min Cyt15-HETE -----> ERMem15-HETE (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 22b: in 1/min Cyt15-HETE -----> GolgiMem15-HETE (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(23) = 1;        % 23a: in 1/min ERMem11-HETE -----> Cyt11-HETE (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 23b: in 1/min GolgiMem11-HETE -----> Cyt11-HETE (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(24) = 1;        % 24a: in 1/min Cyt11-HETE -----> ERMem11-HETE (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 24b: in 1/min Cyt11-HETE -----> GolgiMem11-HETE (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(25) = 1;        % 25a: in 1/min ERMemLTA4 -----> CytLTA4 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 25b: in 1/min GolgiMemLTA4 -----> CytLTA4 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(26) = 1;        % 26a: in 1/min CytLTA4 -----> ERMemLTA4 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 26b: in 1/min CytLTA4 -----> GolgiMemLTA4 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(27) = 1;        % 27a: in 1/min ERMemLTB4 -----> CytLTB4 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 27b: in 1/min GolgiMemLTB4 -----> CytLTB4 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(28) = 1;        % 28a: in 1/min CytLTB4 -----> ERMemLTB4 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 28b: in 1/min CytLTB4 -----> GolgiMemLTB4 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(29) = 1;        % 29a: in 1/min ERMemTXA2 -----> CytTXA2 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 29b: in 1/min GolgiMemTXA2 -----> CytTXA2 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(30) = 1;        % 30a: in 1/min CytTXA2 -----> ERMemTXA2 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 30b: in 1/min CytTXA2 -----> GolgiMemTXA2 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(31) = 1;        % 31a: in 1/min ERMemTXB2 -----> CytTXB2 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 31b: in 1/min GolgiMemTXB2 -----> CytTXB2 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(32) = 1;        % 32a: in 1/min CytTXB2 -----> ERMemTXB2 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 32b: in 1/min CytTXB2 -----> GolgiMemTXB2 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(33) = 1;        % 33a: in 1/min ERMemPGF2ALPHA -----> CytPGF2ALPHA (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 33b: in 1/min GolgiMemPGF2ALPHA -----> CytPGF2ALPHA (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(34) = 1;        % 34a: in 1/min CytPGF2ALPHA -----> ERMemPGF2ALPHA (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 34b: in 1/min CytPGF2ALPHA -----> GolgiMemPGF2ALPHA (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(35) = 1;        % 35a: in 1/min ERMem11-DEHYDRO-TXB2 -----> Cyt11-DEHYDRO-TXB2 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 35b: in 1/min GolgiMem11-DEHYDRO-TXB2 -----> Cyt11-DEHYDRO-TXB2 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(36) = 1;        % 36a: in 1/min Cyt11-DEHYDRO-TXB2 -----> ERMem11-DEHYDRO-TXB2 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 36b: in 1/min Cyt11-DEHYDRO-TXB2 -----> GolgiMem11-DEHYDRO-TXB2 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(37) = 70.9298;  % 37a: kcat: in 1/min AA ----ACSL1----> AA-COA  at ERMem  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 37b: kcat: in 1/min AA ----ACSL1----> AA-COA  at GolgiMem  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
ka(38) = 6.8055;   % 38a: kcat: in 1/min AA ----ACSL2----> AA-COA  at ERMem  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 38b: kcat: in 1/min AA ----ACSL2----> AA-COA  at GolgiMem  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
ka(39) = 30.7156;  % 39a: kcat: in 1/min AA ----ACSL3----> AA-COA  at ERMem  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 39b: kcat: in 1/min AA ----ACSL3----> AA-COA  at GolgiMem  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
ka(40) = 174.3541; % 40a: kcat: in 1/min AA ----ACSL4----> AA-COA  at ERMem  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 40b: kcat: in 1/min AA ----ACSL4----> AA-COA  at GolgiMem  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
ka(41) = 35.5128;  % 41a: kcat: in 1/min AA ----ACSL5----> AA-COA  at ERMem  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 41b: kcat: in 1/min AA ----ACSL5----> AA-COA  at GolgiMem  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
ka(42) = 34.8454;  % 42a: kcat: in 1/min AA ----ACSL6----> AA-COA  at ERMem  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 42b: kcat: in 1/min AA ----ACSL6----> AA-COA  at GolgiMem  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
ka(50) = 500;      % 50a: kcat: in 1/min PGH2 ----HPGDS----> PGD2  at ERMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
ka(51) = 300;      % 51a: kcat: in 1/min PL ----PLA2G4A----> AA  at ERMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
                   % 51b: kcat: in 1/min PL ----PLA2G4A----> AA  at GolgiMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
ka(52) = 21;       % 52a: kcat: in 1/min PGH2 ----PTGDS----> PGD2  at ERMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
                   % 52b: kcat: in 1/min PGH2 ----PTGDS----> PGD2  at GolgiMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
ka(53) = 40;       % 53a: kcat: in 1/min PGH2 ----PTGES2----> PGE2  at GolgiMem  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
ka(56) = 540;      % 56a: kcat: in 1/min PGH2 ----TBXAS1----> TXA2  at ERMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
ka(58) = 1.2;      % 58a: kcat: in 1/min PGE2 ----CBR1----> PGF2ALPHA  in Cyt  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
ka(59) = 1.2;      % 59a: kcat: in 1/min PGE2 ----CBR3----> PGF2ALPHA  in Cyt  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
ka(66) = 100;      % 66a: kcat: in 1/min PGD2 ----HPGD----> 13,14-DIHYDRO-15-KETO-PGD2  in Cyt  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
ka(67) = 100;      % 67a: kcat: in 1/min PGE2 ----HPGD----> 13,14-DIHYDRO-15-KETO-PGE2  in Cyt  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
ka(68) = 600;      % 68a: kcat: in 1/min PGF2ALPHA ----HPGD----> 13,14-DIHYDRO-15-KETO-PGF2ALPHA  in Cyt  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
ka(69) = 650;      % 69a: kcat: in 1/min PGJ2 ----HPGD----> 13,14-DIHYDRO-15-KETO-PGJ2  in Cyt  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
ka(70) = 150;      % 70a: kcat: in 1/min LTA4 ----LTA4H----> LTB4  in Cyt  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
ka(71) = 150;      % 71a: kcat: in 1/min LTA4 ----LTC4S----> LTC4  at ERMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
ka(72) = 6;        % 72a: kcat: in 1/min AA ----PTGS1----> PGH2  at ERMem  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
ka(73) = 600;      % 73a: kcat: in 1/min AA ----PTGS2----> PGH2  at ERMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
                   % 73b: kcat: in 1/min AA ----PTGS2----> PGH2  at GolgiMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
                   % 73c: kcat: in 1/min AA ----PTGS2RETURNED----> PGH2  at ERMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
                   % 73d: kcat: in 1/min AA ----PTGS2RETURNED----> PGH2  at GolgiMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
ka(74) = 0.2;      % 74a: kcat: in 1/min PTGS2 ----GANAB----> PTGS2ERTOGOLGI  at ERMem  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 74b: kcat: in 1/min PTGS2 ----MOGS----> PTGS2ERTOGOLGI  at ERMem  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
ka(75) = 0.01;     % 75a: in 1/min ERMemPTGS2ERTOGOLGI ----> GolgiMemPTGS2 (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
ka(76) = 0.12;     % 76a: kcat: in 1/min PTGS2 ----MAN1B1----> PTGS2GOLGITOER  at GolgiMem  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
ka(77) = 0.005;    % 77a: in 1/min GolgiMemPTGS2GOLGITOER ----> ERMemPTGS2RETURNED (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
ka(78) = 0.1;      % 78a: in 1/min PTGS2RETURNED ----> PTGS2DEGRADED at ERMem  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
ka(79) = 1;        % 79a: in 1/min TXA2 ----> TXB2 at ERMem  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 79b: in 1/min TXA2 ----> TXB2 at GolgiMem  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 79c: in 1/min TXA2 ----> TXB2 in Cyt  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 79d: in 1/min TXA2 ----> TXB2 in Ecs  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
ka(80) = 0.0015;   % 80a: in 1/min TXB2 ----> 11-DEHYDRO-TXB2 at ERMem  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 80b: in 1/min TXB2 ----> 11-DEHYDRO-TXB2 at GolgiMem  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 80c: in 1/min TXB2 ----> 11-DEHYDRO-TXB2 in Cyt  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 80d: in 1/min TXB2 ----> 11-DEHYDRO-TXB2 in Ecs  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
ka(81) = 0.05;     % 81a: in 1/min AA ----> 11-HPETE at ERMem  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 81b: in 1/min AA ----> 11-HPETE at GolgiMem  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 81c: in 1/min AA ----> 11-HPETE in Cyt  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
ka(82) = 0.05;     % 82a: in 1/min 11-HPETE ----> 11-HETE at ERMem  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 82b: in 1/min 11-HPETE ----> 11-HETE at GolgiMem  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 82c: in 1/min 11-HPETE ----> 11-HETE in Cyt  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
ka(85) = 6E-05;    % 85a: in 1/min PGE2 ----> PGA2 at ERMem  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 85b: in 1/min PGE2 ----> PGA2 at GolgiMem  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 85c: in 1/min PGE2 ----> PGA2 in Cyt  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
ka(87) = 0.001;    % 87a: in 1/min PGD2 ----> PGJ2 at ERMem  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 87b: in 1/min PGD2 ----> PGJ2 at GolgiMem  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 87c: in 1/min PGD2 ----> PGJ2 in Cyt  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 87d: in 1/min PGD2 ----> PGJ2 in Ecs  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
ka(88) = 1E+07;    % 88a: in 1/min CytPLA2G4A --CytCA---> ERMemPLA2G4A (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 88b: in 1/min CytPLA2G4A --CytCA---> GolgiMemPLA2G4A (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(89) = 10;       % 89a: in 1/min ERMemPLA2G4A --CytCA---> CytPLA2G4A (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 89b: in 1/min GolgiMemPLA2G4A --CytCA---> CytPLA2G4A (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(90) = 1E-30;    % 90a: in 1/min CytPLA2G4A -----> ERMemPLA2G4A (Reaction_membrane_association_dissociation) (Curated) (Bmdm_kdo_lipida_atp)
                   % 90b: in 1/min CytPLA2G4A -----> GolgiMemPLA2G4A (Reaction_membrane_association_dissociation) (Curated) (Bmdm_kdo_lipida_atp)
ka(91) = 0.01;     % 91a: in 1/min ERMemPLA2G4A -----> CytPLA2G4A (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 91b: in 1/min GolgiMemPLA2G4A -----> CytPLA2G4A (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(92) = 0.01;     % 92a: in 1/min 11-HETE ----> SINK at ERMem  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 92b: in 1/min 11-HETE ----> SINK at GolgiMem  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 92c: in 1/min 11-HETE ----> SINK in Cyt  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 92d: in 1/min 11-HETE ----> SINK in Ecs  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
ka(93) = 0.04;     % 93a: in 1/min 5-HETE ----> SINK at ERMem  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 93b: in 1/min 5-HETE ----> SINK at GolgiMem  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 93c: in 1/min 5-HETE ----> SINK in Cyt  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 93d: in 1/min 5-HETE ----> SINK in Ecs  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
ka(94) = 0.35;     % 94a: in 1/min 15-HETE ----> SINK at ERMem  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 94b: in 1/min 15-HETE ----> SINK at GolgiMem  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 94c: in 1/min 15-HETE ----> SINK in Cyt  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 94d: in 1/min 15-HETE ----> SINK in Ecs  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
ka(95) = 0.0005;   % 95a: in 1/min 13,14-DIHYDRO-15-KETO-PGD2 ----> SINK in Cyt  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 95b: in 1/min 13,14-DIHYDRO-15-KETO-PGD2 ----> SINK in Ecs  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
ka(96) = 0.0005;   % 96a: in 1/min 13,14-DIHYDRO-15-KETO-PGE2 ----> SINK in Cyt  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 96b: in 1/min 13,14-DIHYDRO-15-KETO-PGE2 ----> SINK in Ecs  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
ka(97) = 0.003;    % 97a: in 1/min 13,14-DIHYDRO-15-KETO-PGF2ALPHA ----> SINK in Cyt  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 97b: in 1/min 13,14-DIHYDRO-15-KETO-PGF2ALPHA ----> SINK in Ecs  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
ka(98) = 0.3;      % 98a: kcat: in 1/min AA ----ALOX5----> 5-HPETE  at ERMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
ka(99) = 1;        % 99a: kcat: in 1/min 5-HPETE ----ALOX5----> LTA4  at ERMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
ka(100) = 0.4;     % 100a: in 1/min 5-HPETE ----> 5-HETE at ERMem  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
ka(101) = 0.05;    % 101a: in mol/(l*min) LTB4 ----> SINK at ERMem  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 101b: in mol/(l*min) LTB4 ----> SINK at GolgiMem  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 101c: in mol/(l*min) LTB4 ----> SINK in Cyt  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 101d: in mol/(l*min) LTB4 ----> SINK in Ecs  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
ka(102) = 5000000; % 102a: in 1/min CytALOX5 --CytCA---> ERMemALOX5 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(103) = 10;      % 103a: in 1/min ERMemALOX5 --CytCA---> CytALOX5 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(104) = 1E-30;   % 104a: in 1/min CytALOX5 -----> ERMemALOX5 (Reaction_membrane_association_dissociation) (Curated) (Bmdm_kdo_lipida_atp)
ka(105) = 0.005;   % 105a: in 1/min ERMemALOX5 -----> CytALOX5 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(106) = 200;     % 106a: kcat: in 1/min AA ----ALOX15----> 15-HETE  at ERMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
ka(112) = 1000000; % 112a: in 1/min CytALOX15 --CytCA---> ERMemALOX15 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(113) = 10;      % 113a: in 1/min ERMemALOX15 --CytCA---> CytALOX15 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(114) = 1E-30;   % 114a: in 1/min CytALOX15 -----> ERMemALOX15 (Reaction_membrane_association_dissociation) (Curated) (Bmdm_kdo_lipida_atp)
ka(115) = 0.001;   % 115a: in 1/min ERMemALOX15 -----> CytALOX15 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(116) = 0.5;     % 116a: in 1/min CytHPGDS --CytCA---> ERMemHPGDS (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(117) = 0.5;     % 117a: in 1/min ERMemHPGDS --CytCA---> CytHPGDS (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(118) = 1E-10;   % 118a: in 1/min CytHPGDS -----> ERMemHPGDS (Reaction_membrane_association_dissociation) (Curated) (Bmdm_kdo_lipida_atp)
ka(119) = 0.0005;  % 119a: in 1/min ERMemHPGDS -----> CytHPGDS (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(129) = 1;       % 129a: in 1/min 11-DEHYDRO-TXB2 transport - from Cyt into Ecs (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(130) = 1;       % 130a: in 1/min 11-HETE transport - from Cyt into Ecs (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(131) = 1;       % 131a: in 1/min 11-HPETE transport - from Cyt into Ecs (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(136) = 1;       % 136a: in 1/min 13,14-DIHYDRO-15-KETO-PGD2 transport - from Cyt into Ecs (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(137) = 1;       % 137a: in 1/min 13,14-DIHYDRO-15-KETO-PGE2 transport - from Cyt into Ecs (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(138) = 1;       % 138a: in 1/min 13,14-DIHYDRO-15-KETO-PGF2ALPHA transport - from Cyt into Ecs (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(139) = 1;       % 139a: in 1/min 13,14-DIHYDRO-15-KETO-PGJ2 transport - from Cyt into Ecs (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(140) = 1;       % 140a: in 1/min 15-HETE transport - from Cyt into Ecs (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(142) = 1;       % 142a: in 1/min 5-HETE transport - from Cyt into Ecs (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(143) = 0.01;    % 143a: in 1/min 5-HPETE transport - from Cyt into Ecs (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(145) = 1;       % 145a: in 1/min AA transport - from Cyt into Ecs (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(147) = 1;       % 147a: in 1/min LTA4 transport - from Cyt into Ecs (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(148) = 1;       % 148a: in 1/min LTB4 transport - from Cyt into Ecs (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(149) = 1;       % 149a: in 1/min LTC4 transport - from Cyt into Ecs (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(152) = 1;       % 152a: in 1/min PGA2 transport - from Cyt into Ecs (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(153) = 1;       % 153a: in 1/min PGD2 transport - from Cyt into Ecs (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(154) = 1;       % 154a: in 1/min PGE2 transport - from Cyt into Ecs (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(155) = 1;       % 155a: in 1/min PGF2ALPHA transport - from Cyt into Ecs (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(157) = 1;       % 157a: in 1/min PGJ2 transport - from Cyt into Ecs (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(158) = 1;       % 158a: in 1/min TXA2 transport - from Cyt into Ecs (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(159) = 1;       % 159a: in 1/min TXB2 transport - from Cyt into Ecs (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(160) = 1;       % 160a: in 1/min 11-DEHYDRO-TXB2 transport - from Ecs into Cyt (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(161) = 1;       % 161a: in 1/min 11-HETE transport - from Ecs into Cyt (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(162) = 1;       % 162a: in 1/min 11-HPETE transport - from Ecs into Cyt (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(167) = 1;       % 167a: in 1/min 13,14-DIHYDRO-15-KETO-PGD2 transport - from Ecs into Cyt (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(168) = 1;       % 168a: in 1/min 13,14-DIHYDRO-15-KETO-PGE2 transport - from Ecs into Cyt (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(169) = 1;       % 169a: in 1/min 13,14-DIHYDRO-15-KETO-PGF2ALPHA transport - from Ecs into Cyt (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(170) = 1;       % 170a: in 1/min 13,14-DIHYDRO-15-KETO-PGJ2 transport - from Ecs into Cyt (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(171) = 1;       % 171a: in 1/min 15-HETE transport - from Ecs into Cyt (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(173) = 1;       % 173a: in 1/min 5-HETE transport - from Ecs into Cyt (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(174) = 0.01;    % 174a: in 1/min 5-HPETE transport - from Ecs into Cyt (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(176) = 1;       % 176a: in 1/min AA transport - from Ecs into Cyt (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(178) = 1;       % 178a: in 1/min LTA4 transport - from Ecs into Cyt (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(179) = 1;       % 179a: in 1/min LTB4 transport - from Ecs into Cyt (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(180) = 1;       % 180a: in 1/min LTC4 transport - from Ecs into Cyt (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(183) = 1;       % 183a: in 1/min PGA2 transport - from Ecs into Cyt (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(184) = 1;       % 184a: in 1/min PGD2 transport - from Ecs into Cyt (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(185) = 1;       % 185a: in 1/min PGE2 transport - from Ecs into Cyt (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(186) = 1;       % 186a: in 1/min PGF2ALPHA transport - from Ecs into Cyt (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(188) = 1;       % 188a: in 1/min PGJ2 transport - from Ecs into Cyt (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(189) = 1;       % 189a: in 1/min TXA2 transport - from Ecs into Cyt (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(190) = 1;       % 190a: in 1/min TXB2 transport - from Ecs into Cyt (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(191) = 1;       % 191a: in 1/min Protein degradation of ERMemTBXAS1 (Reaction_protein_degradation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(192) = 1;       % 192a: in 1/min Protein degradation of ERMemPTGS2 (Reaction_protein_degradation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 192b: in 1/min Protein degradation of ERMemPTGS2DEGRADED (Reaction_protein_degradation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 192c: in 1/min Protein degradation of ERMemPTGS2ERTOGOLGI (Reaction_protein_degradation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 192d: in 1/min Protein degradation of ERMemPTGS2RETURNED (Reaction_protein_degradation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 192e: in 1/min Protein degradation of GolgiMemPTGS2 (Reaction_protein_degradation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 192f: in 1/min Protein degradation of GolgiMemPTGS2GOLGITOER (Reaction_protein_degradation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(193) = 1;       % 193a: in 1/min Protein degradation of ERMemPTGS1 (Reaction_protein_degradation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(196) = 1;       % 196a: in 1/min Protein degradation of GolgiMemPTGES2 (Reaction_protein_degradation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(198) = 1;       % 198a: in 1/min Protein degradation of ERMemPTGDS (Reaction_protein_degradation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 198b: in 1/min Protein degradation of GolgiMemPTGDS (Reaction_protein_degradation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(199) = 1;       % 199a: in 1/min Protein degradation of CytPLA2G4A (Reaction_protein_degradation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 199b: in 1/min Protein degradation of ERMemPLA2G4A (Reaction_protein_degradation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 199c: in 1/min Protein degradation of GolgiMemPLA2G4A (Reaction_protein_degradation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(201) = 1;       % 201a: in 1/min Protein degradation of GolgiMemMAN1B1 (Reaction_protein_degradation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(202) = 1;       % 202a: in 1/min Protein degradation of ERMemLTC4S (Reaction_protein_degradation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(203) = 1;       % 203a: in 1/min Protein degradation of CytLTA4H (Reaction_protein_degradation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(205) = 1;       % 205a: in 1/min Protein degradation of CytHPGD (Reaction_protein_degradation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(210) = 1;       % 210a: in 1/min Protein degradation of ERMemGANAB (Reaction_protein_degradation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(214) = 1;       % 214a: in 1/min Protein degradation of CytCBR3 (Reaction_protein_degradation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(215) = 1;       % 215a: in 1/min Protein degradation of CytCBR1 (Reaction_protein_degradation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(216) = 1;       % 216a: in 1/min Protein degradation of CytALOX5 (Reaction_protein_degradation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 216b: in 1/min Protein degradation of ERMemALOX5 (Reaction_protein_degradation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(218) = 1;       % 218a: in 1/min Protein degradation of CytALOX15 (Reaction_protein_degradation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 218b: in 1/min Protein degradation of ERMemALOX15 (Reaction_protein_degradation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(223) = 1;       % 223a: in 1/min Protein degradation of ERMemACSL6 (Reaction_protein_degradation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 223b: in 1/min Protein degradation of GolgiMemACSL6 (Reaction_protein_degradation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(224) = 1;       % 224a: in 1/min Protein degradation of ERMemACSL5 (Reaction_protein_degradation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 224b: in 1/min Protein degradation of GolgiMemACSL5 (Reaction_protein_degradation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(225) = 1;       % 225a: in 1/min Protein degradation of ERMemACSL4 (Reaction_protein_degradation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 225b: in 1/min Protein degradation of GolgiMemACSL4 (Reaction_protein_degradation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(226) = 1;       % 226a: in 1/min Protein degradation of ERMemACSL3 (Reaction_protein_degradation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 226b: in 1/min Protein degradation of GolgiMemACSL3 (Reaction_protein_degradation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(228) = 1;       % 228a: in 1/min Protein degradation of ERMemACSL1 (Reaction_protein_degradation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 228b: in 1/min Protein degradation of GolgiMemACSL1 (Reaction_protein_degradation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(229) = 1;       % 229a: in 1/min Translation of CytTBXAS1_MRNA to generate ERMemTBXAS1 (Reaction_translation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(230) = 1;       % 230a: in 1/min Translation of CytPTGS2_MRNA to generate ERMemPTGS2 (Reaction_translation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 230b: in 1/min Translation of CytPTGS2_MRNA to generate ERMemPTGS2DEGRADED (Reaction_translation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 230c: in 1/min Translation of CytPTGS2_MRNA to generate ERMemPTGS2ERTOGOLGI (Reaction_translation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 230d: in 1/min Translation of CytPTGS2_MRNA to generate ERMemPTGS2RETURNED (Reaction_translation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 230e: in 1/min Translation of CytPTGS2_MRNA to generate GolgiMemPTGS2 (Reaction_translation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 230f: in 1/min Translation of CytPTGS2_MRNA to generate GolgiMemPTGS2GOLGITOER (Reaction_translation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(231) = 1;       % 231a: in 1/min Translation of CytPTGS1_MRNA to generate ERMemPTGS1 (Reaction_translation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(234) = 1;       % 234a: in 1/min Translation of CytPTGES2_MRNA to generate GolgiMemPTGES2 (Reaction_translation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(236) = 1;       % 236a: in 1/min Translation of CytPTGDS_MRNA to generate ERMemPTGDS (Reaction_translation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 236b: in 1/min Translation of CytPTGDS_MRNA to generate GolgiMemPTGDS (Reaction_translation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(237) = 1;       % 237a: in 1/min Translation of CytPLA2G4A_MRNA to generate CytPLA2G4A (Reaction_translation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 237b: in 1/min Translation of CytPLA2G4A_MRNA to generate ERMemPLA2G4A (Reaction_translation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 237c: in 1/min Translation of CytPLA2G4A_MRNA to generate GolgiMemPLA2G4A (Reaction_translation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(239) = 1;       % 239a: in 1/min Translation of CytMAN1B1_MRNA to generate GolgiMemMAN1B1 (Reaction_translation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(240) = 1;       % 240a: in 1/min Translation of CytLTC4S_MRNA to generate ERMemLTC4S (Reaction_translation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(241) = 1;       % 241a: in 1/min Translation of CytLTA4H_MRNA to generate CytLTA4H (Reaction_translation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(243) = 1;       % 243a: in 1/min Translation of CytHPGD_MRNA to generate CytHPGD (Reaction_translation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(248) = 1;       % 248a: in 1/min Translation of CytGANAB_MRNA to generate ERMemGANAB (Reaction_translation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(252) = 1;       % 252a: in 1/min Translation of CytCBR3_MRNA to generate CytCBR3 (Reaction_translation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(253) = 1;       % 253a: in 1/min Translation of CytCBR1_MRNA to generate CytCBR1 (Reaction_translation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(254) = 1;       % 254a: in 1/min Translation of CytALOX5_MRNA to generate CytALOX5 (Reaction_translation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 254b: in 1/min Translation of CytALOX5_MRNA to generate ERMemALOX5 (Reaction_translation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(256) = 1;       % 256a: in 1/min Translation of CytALOX15_MRNA to generate CytALOX15 (Reaction_translation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 256b: in 1/min Translation of CytALOX15_MRNA to generate ERMemALOX15 (Reaction_translation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(261) = 1;       % 261a: in 1/min Translation of CytACSL6_MRNA to generate ERMemACSL6 (Reaction_translation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 261b: in 1/min Translation of CytACSL6_MRNA to generate GolgiMemACSL6 (Reaction_translation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(262) = 1;       % 262a: in 1/min Translation of CytACSL5_MRNA to generate ERMemACSL5 (Reaction_translation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 262b: in 1/min Translation of CytACSL5_MRNA to generate GolgiMemACSL5 (Reaction_translation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(263) = 1;       % 263a: in 1/min Translation of CytACSL4_MRNA to generate ERMemACSL4 (Reaction_translation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 263b: in 1/min Translation of CytACSL4_MRNA to generate GolgiMemACSL4 (Reaction_translation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(264) = 1;       % 264a: in 1/min Translation of CytACSL3_MRNA to generate ERMemACSL3 (Reaction_translation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 264b: in 1/min Translation of CytACSL3_MRNA to generate GolgiMemACSL3 (Reaction_translation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(266) = 1;       % 266a: in 1/min Translation of CytACSL1_MRNA to generate ERMemACSL1 (Reaction_translation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 266b: in 1/min Translation of CytACSL1_MRNA to generate GolgiMemACSL1 (Reaction_translation) (Assumed) (Bmdm_kdo_lipida_atp)

ka_known_parameter_indexes = [ 50 51 52 56 58 68 69 70 71 73 90 98 99 104 106 114 118 ];
ka_unkown_parameter_indexes = [ 1 2 3 4 5 6 7 8 9 10 11 12 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 53 59 66 67 72 74 75 76 77 78 79 80 81 82 85 87 88 89 91 92 93 94 95 96 97 100 101 102 103 105 112 113 115 116 117 119 129 130 131 136 137 138 139 140 142 143 145 147 148 149 152 153 154 155 157 158 159 160 161 162 167 168 169 170 171 173 174 176 178 179 180 183 184 185 186 188 189 190 191 192 193 196 198 199 201 202 203 205 210 214 215 216 218 223 224 225 226 228 229 230 231 234 236 237 239 240 241 243 248 252 253 254 256 261 262 263 264 266 ];

kb = zeros(106,1);
kb(37) = 3.37E-05; % 37a: Km: in mol/l AA ----ACSL1----> AA-COA  at ERMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
                   % 37b: Km: in mol/l AA ----ACSL1----> AA-COA  at GolgiMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
kb(38) = 3.37E-05; % 38a: Km: in mol/l AA ----ACSL2----> AA-COA  at ERMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
                   % 38b: Km: in mol/l AA ----ACSL2----> AA-COA  at GolgiMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
kb(39) = 3.37E-05; % 39a: Km: in mol/l AA ----ACSL3----> AA-COA  at ERMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
                   % 39b: Km: in mol/l AA ----ACSL3----> AA-COA  at GolgiMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
kb(40) = 1.5E-05;  % 40a: Km: in mol/l AA ----ACSL4----> AA-COA  at ERMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
                   % 40b: Km: in mol/l AA ----ACSL4----> AA-COA  at GolgiMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
kb(41) = 3.37E-05; % 41a: Km: in mol/l AA ----ACSL5----> AA-COA  at ERMem  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 41b: Km: in mol/l AA ----ACSL5----> AA-COA  at GolgiMem  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
kb(42) = 3.37E-05; % 42a: Km: in mol/l AA ----ACSL6----> AA-COA  at ERMem  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 42b: Km: in mol/l AA ----ACSL6----> AA-COA  at GolgiMem  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
kb(43) = 1.5E-05;  % 43a: in mol/l ERMemFA -----(-)-----| ERMemACSL1 (Reaction_competitive_inhibition) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 43b: in mol/l ERMemFA -----(-)-----| ERMemACSL2 (Reaction_competitive_inhibition) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 43c: in mol/l ERMemFA -----(-)-----| ERMemACSL3 (Reaction_competitive_inhibition) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 43d: in mol/l ERMemFA -----(-)-----| ERMemACSL5 (Reaction_competitive_inhibition) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 43e: in mol/l ERMemFA -----(-)-----| ERMemACSL6 (Reaction_competitive_inhibition) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 43f: in mol/l GolgiMemFA -----(-)-----| GolgiMemACSL1 (Reaction_competitive_inhibition) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 43g: in mol/l GolgiMemFA -----(-)-----| GolgiMemACSL2 (Reaction_competitive_inhibition) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 43h: in mol/l GolgiMemFA -----(-)-----| GolgiMemACSL3 (Reaction_competitive_inhibition) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 43i: in mol/l GolgiMemFA -----(-)-----| GolgiMemACSL5 (Reaction_competitive_inhibition) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 43j: in mol/l GolgiMemFA -----(-)-----| GolgiMemACSL6 (Reaction_competitive_inhibition) (Assumed) (Bmdm_kdo_lipida_atp)
kb(44) = 3.37E-05; % 44a: in mol/l ERMemFA -----(-)-----| ERMemACSL4 (Reaction_competitive_inhibition) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 44b: in mol/l GolgiMemFA -----(-)-----| GolgiMemACSL4 (Reaction_competitive_inhibition) (Assumed) (Bmdm_kdo_lipida_atp)
kb(50) = 0.0004;   % 50a: Km: in mol/l PGH2 ----HPGDS----> PGD2  at ERMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
kb(51) = 0.0001;   % 51a: Km: in mol/l PL ----PLA2G4A----> AA  at ERMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
                   % 51b: Km: in mol/l PL ----PLA2G4A----> AA  at GolgiMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
kb(52) = 1.38E-05; % 52a: Km: in mol/l PGH2 ----PTGDS----> PGD2  at ERMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
                   % 52b: Km: in mol/l PGH2 ----PTGDS----> PGD2  at GolgiMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
kb(53) = 0.0002;   % 53a: Km: in mol/l PGH2 ----PTGES2----> PGE2  at GolgiMem  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
kb(56) = 2E-08;    % 56a: Km: in mol/l PGH2 ----TBXAS1----> TXA2  at ERMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
kb(58) = 0.0003;   % 58a: Km: in mol/l PGE2 ----CBR1----> PGF2ALPHA  in Cyt  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
kb(59) = 0.0003;   % 59a: Km: in mol/l PGE2 ----CBR3----> PGF2ALPHA  in Cyt  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
kb(66) = 0.005;    % 66a: in mol/l CytPGD2 -----(-)-----| CytHPGD (Reaction_competitive_inhibition) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 66b: Km: in mol/l PGD2 ----HPGD----> 13,14-DIHYDRO-15-KETO-PGD2  in Cyt  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
kb(67) = 0.0003;   % 67a: in mol/l CytPGE2 -----(-)-----| CytHPGD (Reaction_competitive_inhibition) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 67b: Km: in mol/l PGE2 ----HPGD----> 13,14-DIHYDRO-15-KETO-PGE2  in Cyt  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
kb(68) = 5E-05;    % 68a: in mol/l CytPGF2ALPHA -----(-)-----| CytHPGD (Reaction_competitive_inhibition) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 68b: Km: in mol/l PGF2ALPHA ----HPGD----> 13,14-DIHYDRO-15-KETO-PGF2ALPHA  in Cyt  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
kb(69) = 7E-05;    % 69a: in mol/l CytPGJ2 -----(-)-----| CytHPGD (Reaction_competitive_inhibition) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 69b: Km: in mol/l PGJ2 ----HPGD----> 13,14-DIHYDRO-15-KETO-PGJ2  in Cyt  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
kb(70) = 2.3E-05;  % 70a: Km: in mol/l LTA4 ----LTA4H----> LTB4  in Cyt  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
kb(71) = 2E-05;    % 71a: Km: in mol/l LTA4 ----LTC4S----> LTC4  at ERMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
kb(72) = 0.0045;   % 72a: Km: in mol/l AA ----PTGS1----> PGH2  at ERMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
kb(73) = 0.0051;   % 73a: Km: in mol/l AA ----PTGS2----> PGH2  at ERMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
                   % 73b: Km: in mol/l AA ----PTGS2----> PGH2  at GolgiMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
                   % 73c: Km: in mol/l AA ----PTGS2RETURNED----> PGH2  at ERMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
                   % 73d: Km: in mol/l AA ----PTGS2RETURNED----> PGH2  at GolgiMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
kb(74) = 4E-05;    % 74a: Km: in mol/l PTGS2 ----GANAB----> PTGS2ERTOGOLGI  at ERMem  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 74b: Km: in mol/l PTGS2 ----MOGS----> PTGS2ERTOGOLGI  at ERMem  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
kb(76) = 8E-05;    % 76a: Km: in mol/l PTGS2 ----MAN1B1----> PTGS2GOLGITOER  at GolgiMem  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
kb(98) = 4E-05;    % 98a: in mol/l ERMemAA -----(-)-----| ERMemALOX5 (Reaction_competitive_inhibition) (Curated) (Bmdm_kdo_lipida_atp)
                   % 98b: Km: in mol/l AA ----ALOX5----> 5-HPETE  at ERMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
kb(99) = 1E-06;    % 99a: in mol/l ERMem5-HPETE -----(-)-----| ERMemALOX5 (Reaction_competitive_inhibition) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 99b: Km: in mol/l 5-HPETE ----ALOX5----> LTA4  at ERMem  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
kb(106) = 5E-05;   % 106a: Km: in mol/l AA ----ALOX15----> 15-HETE  at ERMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)

kb_known_parameter_indexes = [ 37 38 39 40 50 51 52 56 58 70 71 72 73 98 106 ];
kb_unkown_parameter_indexes = [ 41 42 43 44 53 59 66 67 68 69 74 76 99 ];

