% Definition of parameter


ka = zeros(258,1);
ka(1) = 1;         % 1a: in 1/min ERMemAA -----> CytAA (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 1b: in 1/min GolgiMemAA -----> CytAA (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(2) = 100;       % 2a: in 1/min CytAA -----> ERMemAA (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 2b: in 1/min CytAA -----> GolgiMemAA (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(3) = 1;         % 3a: in 1/min ERMemPGE2 -----> CytPGE2 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 3b: in 1/min GolgiMemPGE2 -----> CytPGE2 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(4) = 1;         % 4a: in 1/min CytPGE2 -----> ERMemPGE2 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 4b: in 1/min CytPGE2 -----> GolgiMemPGE2 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(5) = 1;         % 5a: in 1/min ERMemPGA2 -----> CytPGA2 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 5b: in 1/min GolgiMemPGA2 -----> CytPGA2 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(6) = 1;         % 6a: in 1/min CytPGA2 -----> ERMemPGA2 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 6b: in 1/min CytPGA2 -----> GolgiMemPGA2 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(7) = 1;         % 7a: in 1/min ERMemPGD2 -----> CytPGD2 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 7b: in 1/min GolgiMemPGD2 -----> CytPGD2 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(8) = 1;         % 8a: in 1/min CytPGD2 -----> ERMemPGD2 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 8b: in 1/min CytPGD2 -----> GolgiMemPGD2 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(11) = 1;        % 11a: in 1/min ERMemPGJ2 -----> CytPGJ2 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 11b: in 1/min GolgiMemPGJ2 -----> CytPGJ2 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(12) = 1;        % 12a: in 1/min CytPGJ2 -----> ERMemPGJ2 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 12b: in 1/min CytPGJ2 -----> GolgiMemPGJ2 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(13) = 1;        % 13a: in 1/min ERMemLTC4 -----> CytLTC4 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 13b: in 1/min GolgiMemLTC4 -----> CytLTC4 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(14) = 1;        % 14a: in 1/min CytLTC4 -----> ERMemLTC4 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 14b: in 1/min CytLTC4 -----> GolgiMemLTC4 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(15) = 1;        % 15a: in 1/min ERMem5-HETE -----> Cyt5-HETE (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 15b: in 1/min GolgiMem5-HETE -----> Cyt5-HETE (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(16) = 1;        % 16a: in 1/min Cyt5-HETE -----> ERMem5-HETE (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 16b: in 1/min Cyt5-HETE -----> GolgiMem5-HETE (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(17) = 1;        % 17a: in 1/min ERMem15-HETE -----> Cyt15-HETE (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 17b: in 1/min GolgiMem15-HETE -----> Cyt15-HETE (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(18) = 1;        % 18a: in 1/min Cyt15-HETE -----> ERMem15-HETE (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 18b: in 1/min Cyt15-HETE -----> GolgiMem15-HETE (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(19) = 1;        % 19a: in 1/min ERMemLTA4 -----> CytLTA4 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 19b: in 1/min GolgiMemLTA4 -----> CytLTA4 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(20) = 1;        % 20a: in 1/min CytLTA4 -----> ERMemLTA4 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 20b: in 1/min CytLTA4 -----> GolgiMemLTA4 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(21) = 1;        % 21a: in 1/min ERMemLTB4 -----> CytLTB4 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 21b: in 1/min GolgiMemLTB4 -----> CytLTB4 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(22) = 1;        % 22a: in 1/min CytLTB4 -----> ERMemLTB4 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 22b: in 1/min CytLTB4 -----> GolgiMemLTB4 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(23) = 1;        % 23a: in 1/min ERMemTXA2 -----> CytTXA2 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 23b: in 1/min GolgiMemTXA2 -----> CytTXA2 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(24) = 1;        % 24a: in 1/min CytTXA2 -----> ERMemTXA2 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 24b: in 1/min CytTXA2 -----> GolgiMemTXA2 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(25) = 1;        % 25a: in 1/min ERMemPGF2ALPHA -----> CytPGF2ALPHA (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 25b: in 1/min GolgiMemPGF2ALPHA -----> CytPGF2ALPHA (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(26) = 1;        % 26a: in 1/min CytPGF2ALPHA -----> ERMemPGF2ALPHA (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 26b: in 1/min CytPGF2ALPHA -----> GolgiMemPGF2ALPHA (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(27) = 1;        % 27a: in 1/min ERMem11-DEHYDRO-TXB2 -----> Cyt11-DEHYDRO-TXB2 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 27b: in 1/min GolgiMem11-DEHYDRO-TXB2 -----> Cyt11-DEHYDRO-TXB2 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(28) = 1;        % 28a: in 1/min Cyt11-DEHYDRO-TXB2 -----> ERMem11-DEHYDRO-TXB2 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 28b: in 1/min Cyt11-DEHYDRO-TXB2 -----> GolgiMem11-DEHYDRO-TXB2 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(29) = 70.9298;  % 29a: kcat: in 1/min AA ----ACSL1----> AA-COA  at ERMem  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 29b: kcat: in 1/min AA ----ACSL1----> AA-COA  at GolgiMem  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
ka(30) = 6.8055;   % 30a: kcat: in 1/min AA ----ACSL2----> AA-COA  at ERMem  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 30b: kcat: in 1/min AA ----ACSL2----> AA-COA  at GolgiMem  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
ka(31) = 30.7156;  % 31a: kcat: in 1/min AA ----ACSL3----> AA-COA  at ERMem  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 31b: kcat: in 1/min AA ----ACSL3----> AA-COA  at GolgiMem  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
ka(32) = 174.3541; % 32a: kcat: in 1/min AA ----ACSL4----> AA-COA  at ERMem  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 32b: kcat: in 1/min AA ----ACSL4----> AA-COA  at GolgiMem  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
ka(33) = 35.5128;  % 33a: kcat: in 1/min AA ----ACSL5----> AA-COA  at ERMem  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 33b: kcat: in 1/min AA ----ACSL5----> AA-COA  at GolgiMem  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
ka(34) = 34.8454;  % 34a: kcat: in 1/min AA ----ACSL6----> AA-COA  at ERMem  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 34b: kcat: in 1/min AA ----ACSL6----> AA-COA  at GolgiMem  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
ka(39) = 200;      % 39a: kcat: in 1/min AA ----PTGS1----> PGH2  at ERMem  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
ka(40) = 600;      % 40a: kcat: in 1/min AA ----PTGS2----> PGH2  at ERMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
                   % 40b: kcat: in 1/min AA ----PTGS2----> PGH2  at GolgiMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
                   % 40c: kcat: in 1/min AA ----PTGS2BACK----> PGH2  at ERMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
                   % 40d: kcat: in 1/min AA ----PTGS2BACK----> PGH2  at GolgiMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
                   % 40e: kcat: in 1/min AA ----PTGS2EXPORT----> PGH2  at ERMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
                   % 40f: kcat: in 1/min AA ----PTGS2EXPORT----> PGH2  at GolgiMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
ka(44) = 500;      % 44a: kcat: in 1/min PGH2 ----HPGDS----> PGD2  at ERMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
ka(45) = 300;      % 45a: kcat: in 1/min PL ----PLA2G4A----> AA  at ERMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
                   % 45b: kcat: in 1/min PL ----PLA2G4A----> AA  at GolgiMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
ka(46) = 21;       % 46a: kcat: in 1/min PGH2 ----PTGDS----> PGD2  at ERMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
                   % 46b: kcat: in 1/min PGH2 ----PTGDS----> PGD2  at GolgiMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
ka(47) = 40;       % 47a: kcat: in 1/min PGH2 ----PTGES2----> PGE2  at GolgiMem  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
ka(50) = 540;      % 50a: kcat: in 1/min PGH2 ----TBXAS1----> TXA2  at ERMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
ka(52) = 1.2;      % 52a: kcat: in 1/min PGE2 ----CBR1----> PGF2ALPHA  in Cyt  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
ka(53) = 1.2;      % 53a: kcat: in 1/min PGE2 ----CBR3----> PGF2ALPHA  in Cyt  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
ka(60) = 100;      % 60a: kcat: in 1/min PGD2 ----HPGD----> 13,14-DIHYDRO-15-KETO-PGD2  in Cyt  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
ka(61) = 100;      % 61a: kcat: in 1/min PGE2 ----HPGD----> 13,14-DIHYDRO-15-KETO-PGE2  in Cyt  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
ka(62) = 600;      % 62a: kcat: in 1/min PGF2ALPHA ----HPGD----> 13,14-DIHYDRO-15-KETO-PGF2ALPHA  in Cyt  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
ka(63) = 650;      % 63a: kcat: in 1/min PGJ2 ----HPGD----> 13,14-DIHYDRO-15-KETO-PGJ2  in Cyt  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
ka(64) = 150;      % 64a: kcat: in 1/min LTA4 ----LTA4H----> LTB4  in Cyt  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
ka(65) = 150;      % 65a: kcat: in 1/min LTA4 ----LTC4S----> LTC4  at ERMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
ka(66) = 0.005;    % 66a: kcat: in 1/min PTGS2 ----GANAB----> PTGS2EXPORT  at ERMem  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 66b: kcat: in 1/min PTGS2 ----MOGS----> PTGS2EXPORT  at ERMem  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
ka(67) = 0.1;      % 67a: in 1/min ERMemPTGS2EXPORT ----> GolgiMemPTGS2 (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
ka(68) = 1;        % 68a: kcat: in 1/min PTGS2 ----MAN1B1----> PTGS2BACK  at GolgiMem  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
ka(69) = 0.02;     % 69a: in 1/min GolgiMemPTGS2BACK ----> ERMemPTGS2BACK (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
ka(70) = 0.0002;   % 70a: in 1/min PTGS2BACK ----> PTGS2INACT at ERMem  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
ka(71) = 0.05;     % 71a: in 1/min AA ----> 11-HPETE at ERMem  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 71b: in 1/min AA ----> 11-HPETE at GolgiMem  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 71c: in 1/min AA ----> 11-HPETE in Cyt  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
ka(72) = 10;       % 72a: in 1/min 11-HPETE ----> 11-HETE at ERMem  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 72b: in 1/min 11-HPETE ----> 11-HETE at GolgiMem  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 72c: in 1/min 11-HPETE ----> 11-HETE in Cyt  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
ka(75) = 6E-05;    % 75a: in 1/min PGE2 ----> PGA2 at ERMem  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 75b: in 1/min PGE2 ----> PGA2 at GolgiMem  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 75c: in 1/min PGE2 ----> PGA2 in Cyt  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
ka(77) = 0.001;    % 77a: in 1/min PGD2 ----> PGJ2 at ERMem  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 77b: in 1/min PGD2 ----> PGJ2 at GolgiMem  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 77c: in 1/min PGD2 ----> PGJ2 in Cyt  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 77d: in 1/min PGD2 ----> PGJ2 in Ecs  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
ka(78) = 1E+07;    % 78a: in 1/min CytPLA2G4A --CytCA---> ERMemPLA2G4A (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 78b: in 1/min CytPLA2G4A --CytCA---> GolgiMemPLA2G4A (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(79) = 10;       % 79a: in 1/min ERMemPLA2G4A --CytCA---> CytPLA2G4A (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 79b: in 1/min GolgiMemPLA2G4A --CytCA---> CytPLA2G4A (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(80) = 1E-30;    % 80a: in 1/min CytPLA2G4A -----> ERMemPLA2G4A (Reaction_membrane_association_dissociation) (Curated) (Bmdm_kdo_lipida_atp)
                   % 80b: in 1/min CytPLA2G4A -----> GolgiMemPLA2G4A (Reaction_membrane_association_dissociation) (Curated) (Bmdm_kdo_lipida_atp)
ka(81) = 0.01;     % 81a: in 1/min ERMemPLA2G4A -----> CytPLA2G4A (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 81b: in 1/min GolgiMemPLA2G4A -----> CytPLA2G4A (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(82) = 0.007;    % 82a: in 1/min 11-HETE ----> SINK at ERMem  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 82b: in 1/min 11-HETE ----> SINK at GolgiMem  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 82c: in 1/min 11-HETE ----> SINK in Cyt  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 82d: in 1/min 11-HETE ----> SINK in Ecs  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
ka(83) = 0.04;     % 83a: in 1/min 5-HETE ----> SINK at ERMem  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 83b: in 1/min 5-HETE ----> SINK at GolgiMem  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 83c: in 1/min 5-HETE ----> SINK in Cyt  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 83d: in 1/min 5-HETE ----> SINK in Ecs  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
ka(84) = 0.35;     % 84a: in 1/min 15-HETE ----> SINK at ERMem  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 84b: in 1/min 15-HETE ----> SINK at GolgiMem  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 84c: in 1/min 15-HETE ----> SINK in Cyt  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 84d: in 1/min 15-HETE ----> SINK in Ecs  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
ka(85) = 0.0005;   % 85a: in 1/min 13,14-DIHYDRO-15-KETO-PGD2 ----> SINK at ERMem  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 85b: in 1/min 13,14-DIHYDRO-15-KETO-PGD2 ----> SINK at GolgiMem  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 85c: in 1/min 13,14-DIHYDRO-15-KETO-PGD2 ----> SINK in Cyt  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 85d: in 1/min 13,14-DIHYDRO-15-KETO-PGD2 ----> SINK in Ecs  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
ka(86) = 0.0005;   % 86a: in 1/min 13,14-DIHYDRO-15-KETO-PGE2 ----> SINK at ERMem  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 86b: in 1/min 13,14-DIHYDRO-15-KETO-PGE2 ----> SINK at GolgiMem  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 86c: in 1/min 13,14-DIHYDRO-15-KETO-PGE2 ----> SINK in Cyt  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 86d: in 1/min 13,14-DIHYDRO-15-KETO-PGE2 ----> SINK in Ecs  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
ka(87) = 0.003;    % 87a: in 1/min 13,14-DIHYDRO-15-KETO-PGF2ALPHA ----> SINK at ERMem  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 87b: in 1/min 13,14-DIHYDRO-15-KETO-PGF2ALPHA ----> SINK at GolgiMem  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 87c: in 1/min 13,14-DIHYDRO-15-KETO-PGF2ALPHA ----> SINK in Cyt  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 87d: in 1/min 13,14-DIHYDRO-15-KETO-PGF2ALPHA ----> SINK in Ecs  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
ka(88) = 0.3;      % 88a: kcat: in 1/min AA ----ALOX5----> 5HPETE  at ERMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
ka(89) = 1;        % 89a: kcat: in 1/min 5HPETE ----ALOX5----> LTA4  at ERMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
ka(90) = 0.4;      % 90a: in 1/min 5HPETE ----> 5-HETE at ERMem  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
ka(91) = 0.05;     % 91a: in mol/(l*min) LTB4 ----> SINK at ERMem  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 91b: in mol/(l*min) LTB4 ----> SINK at GolgiMem  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 91c: in mol/(l*min) LTB4 ----> SINK in Cyt  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 91d: in mol/(l*min) LTB4 ----> SINK in Ecs  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
ka(92) = 5000000;  % 92a: in 1/min CytALOX5 --CytCA---> ERMemALOX5 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(93) = 10;       % 93a: in 1/min ERMemALOX5 --CytCA---> CytALOX5 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(94) = 1E-30;    % 94a: in 1/min CytALOX5 -----> ERMemALOX5 (Reaction_membrane_association_dissociation) (Curated) (Bmdm_kdo_lipida_atp)
ka(95) = 0.005;    % 95a: in 1/min ERMemALOX5 -----> CytALOX5 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(96) = 200;      % 96a: kcat: in 1/min AA ----ALOX15----> 15-HETE  at ERMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
ka(102) = 1000000; % 102a: in 1/min CytALOX15 --CytCA---> ERMemALOX15 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(103) = 10;      % 103a: in 1/min ERMemALOX15 --CytCA---> CytALOX15 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(104) = 1E-30;   % 104a: in 1/min CytALOX15 -----> ERMemALOX15 (Reaction_membrane_association_dissociation) (Curated) (Bmdm_kdo_lipida_atp)
ka(105) = 0.001;   % 105a: in 1/min ERMemALOX15 -----> CytALOX15 (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(106) = 0.5;     % 106a: in 1/min CytHPGDS --CytCA---> ERMemHPGDS (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(107) = 0.5;     % 107a: in 1/min ERMemHPGDS --CytCA---> CytHPGDS (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(108) = 1E-10;   % 108a: in 1/min CytHPGDS -----> ERMemHPGDS (Reaction_membrane_association_dissociation) (Curated) (Bmdm_kdo_lipida_atp)
ka(109) = 0.0005;  % 109a: in 1/min ERMemHPGDS -----> CytHPGDS (Reaction_membrane_association_dissociation) (Assumed) (Bmdm_kdo_lipida_atp)
ka(118) = 50;      % 118a: in 1/min TXA2 ----> TXB2 at ERMem  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 118b: in 1/min TXA2 ----> TXB2 at GolgiMem  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 118c: in 1/min TXA2 ----> TXB2 in Cyt  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 118d: in 1/min TXA2 ----> TXB2 in Ecs  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
ka(119) = 0.0008;  % 119a: in 1/min TXB2 ----> 11-DEHYDRO-TXB2 at ERMem  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 119b: in 1/min TXB2 ----> 11-DEHYDRO-TXB2 at GolgiMem  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 119c: in 1/min TXB2 ----> 11-DEHYDRO-TXB2 in Cyt  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 119d: in 1/min TXB2 ----> 11-DEHYDRO-TXB2 in Ecs  (Reaction_non_mm_substrate_product) (Assumed) (Bmdm_kdo_lipida_atp)
ka(121) = 1;       % 121a: in 1/min 11-DEHYDRO-TXB2 transport - from Cyt into Ecs (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(122) = 1;       % 122a: in 1/min 11-HETE transport - from Cyt into Ecs (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(123) = 1;       % 123a: in 1/min 11-HPETE transport - from Cyt into Ecs (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(128) = 1;       % 128a: in 1/min 13,14-DIHYDRO-15-KETO-PGD2 transport - from Cyt into Ecs (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(129) = 1;       % 129a: in 1/min 13,14-DIHYDRO-15-KETO-PGE2 transport - from Cyt into Ecs (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(130) = 1;       % 130a: in 1/min 13,14-DIHYDRO-15-KETO-PGF2ALPHA transport - from Cyt into Ecs (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(131) = 1;       % 131a: in 1/min 13,14-DIHYDRO-15-KETO-PGJ2 transport - from Cyt into Ecs (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(132) = 1;       % 132a: in 1/min 15-HETE transport - from Cyt into Ecs (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(134) = 1;       % 134a: in 1/min 5-HETE transport - from Cyt into Ecs (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(137) = 1;       % 137a: in 1/min AA transport - from Cyt into Ecs (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(139) = 1;       % 139a: in 1/min LTA4 transport - from Cyt into Ecs (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(140) = 1;       % 140a: in 1/min LTB4 transport - from Cyt into Ecs (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(141) = 1;       % 141a: in 1/min LTC4 transport - from Cyt into Ecs (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(144) = 1;       % 144a: in 1/min PGA2 transport - from Cyt into Ecs (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(145) = 1;       % 145a: in 1/min PGD2 transport - from Cyt into Ecs (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(146) = 1;       % 146a: in 1/min PGE2 transport - from Cyt into Ecs (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(147) = 1;       % 147a: in 1/min PGF2ALPHA transport - from Cyt into Ecs (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(149) = 1;       % 149a: in 1/min PGJ2 transport - from Cyt into Ecs (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(150) = 1;       % 150a: in 1/min TXA2 transport - from Cyt into Ecs (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(151) = 1;       % 151a: in 1/min TXB2 transport - from Cyt into Ecs (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(152) = 1;       % 152a: in 1/min 11-DEHYDRO-TXB2 transport - from Ecs into Cyt (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(153) = 1;       % 153a: in 1/min 11-HETE transport - from Ecs into Cyt (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(154) = 1;       % 154a: in 1/min 11-HPETE transport - from Ecs into Cyt (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(159) = 1;       % 159a: in 1/min 13,14-DIHYDRO-15-KETO-PGD2 transport - from Ecs into Cyt (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(160) = 1;       % 160a: in 1/min 13,14-DIHYDRO-15-KETO-PGE2 transport - from Ecs into Cyt (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(161) = 1;       % 161a: in 1/min 13,14-DIHYDRO-15-KETO-PGF2ALPHA transport - from Ecs into Cyt (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(162) = 1;       % 162a: in 1/min 13,14-DIHYDRO-15-KETO-PGJ2 transport - from Ecs into Cyt (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(163) = 1;       % 163a: in 1/min 15-HETE transport - from Ecs into Cyt (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(165) = 1;       % 165a: in 1/min 5-HETE transport - from Ecs into Cyt (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(168) = 1;       % 168a: in 1/min AA transport - from Ecs into Cyt (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(170) = 1;       % 170a: in 1/min LTA4 transport - from Ecs into Cyt (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(171) = 1;       % 171a: in 1/min LTB4 transport - from Ecs into Cyt (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(172) = 1;       % 172a: in 1/min LTC4 transport - from Ecs into Cyt (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(175) = 1;       % 175a: in 1/min PGA2 transport - from Ecs into Cyt (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(176) = 1;       % 176a: in 1/min PGD2 transport - from Ecs into Cyt (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(177) = 1;       % 177a: in 1/min PGE2 transport - from Ecs into Cyt (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(178) = 1;       % 178a: in 1/min PGF2ALPHA transport - from Ecs into Cyt (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(180) = 1;       % 180a: in 1/min PGJ2 transport - from Ecs into Cyt (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(181) = 1;       % 181a: in 1/min TXA2 transport - from Ecs into Cyt (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(182) = 1;       % 182a: in 1/min TXB2 transport - from Ecs into Cyt (Reaction_facilitated_diffusion) (Assumed) (Bmdm_kdo_lipida_atp)
ka(183) = 1;       % 183a: in 1/min Protein degradation of ERMemTBXAS1 (Reaction_protein_degradation) (Curated) (Bmdm_kdo_lipida_atp)
ka(184) = 1;       % 184a: in 1/min Protein degradation of ERMemPTGS2 (Reaction_protein_degradation) (Curated) (Bmdm_kdo_lipida_atp)
                   % 184b: in 1/min Protein degradation of ERMemPTGS2BACK (Reaction_protein_degradation) (Curated) (Bmdm_kdo_lipida_atp)
                   % 184c: in 1/min Protein degradation of ERMemPTGS2EXPORT (Reaction_protein_degradation) (Curated) (Bmdm_kdo_lipida_atp)
                   % 184d: in 1/min Protein degradation of ERMemPTGS2INACT (Reaction_protein_degradation) (Curated) (Bmdm_kdo_lipida_atp)
                   % 184e: in 1/min Protein degradation of GolgiMemPTGS2 (Reaction_protein_degradation) (Curated) (Bmdm_kdo_lipida_atp)
                   % 184f: in 1/min Protein degradation of GolgiMemPTGS2BACK (Reaction_protein_degradation) (Curated) (Bmdm_kdo_lipida_atp)
ka(185) = 1;       % 185a: in 1/min Protein degradation of ERMemPTGS1 (Reaction_protein_degradation) (Curated) (Bmdm_kdo_lipida_atp)
ka(188) = 1;       % 188a: in 1/min Protein degradation of GolgiMemPTGES2 (Reaction_protein_degradation) (Curated) (Bmdm_kdo_lipida_atp)
ka(190) = 1;       % 190a: in 1/min Protein degradation of ERMemPTGDS (Reaction_protein_degradation) (Curated) (Bmdm_kdo_lipida_atp)
                   % 190b: in 1/min Protein degradation of GolgiMemPTGDS (Reaction_protein_degradation) (Curated) (Bmdm_kdo_lipida_atp)
ka(191) = 1;       % 191a: in 1/min Protein degradation of CytPLA2G4A (Reaction_protein_degradation) (Curated) (Bmdm_kdo_lipida_atp)
                   % 191b: in 1/min Protein degradation of ERMemPLA2G4A (Reaction_protein_degradation) (Curated) (Bmdm_kdo_lipida_atp)
                   % 191c: in 1/min Protein degradation of GolgiMemPLA2G4A (Reaction_protein_degradation) (Curated) (Bmdm_kdo_lipida_atp)
ka(193) = 1;       % 193a: in 1/min Protein degradation of GolgiMemMAN1B1 (Reaction_protein_degradation) (Curated) (Bmdm_kdo_lipida_atp)
ka(194) = 1;       % 194a: in 1/min Protein degradation of ERMemLTC4S (Reaction_protein_degradation) (Curated) (Bmdm_kdo_lipida_atp)
ka(195) = 1;       % 195a: in 1/min Protein degradation of CytLTA4H (Reaction_protein_degradation) (Curated) (Bmdm_kdo_lipida_atp)
ka(197) = 1;       % 197a: in 1/min Protein degradation of CytHPGD (Reaction_protein_degradation) (Curated) (Bmdm_kdo_lipida_atp)
ka(202) = 1;       % 202a: in 1/min Protein degradation of ERMemGANAB (Reaction_protein_degradation) (Curated) (Bmdm_kdo_lipida_atp)
ka(206) = 1;       % 206a: in 1/min Protein degradation of CytCBR3 (Reaction_protein_degradation) (Curated) (Bmdm_kdo_lipida_atp)
ka(207) = 1;       % 207a: in 1/min Protein degradation of CytCBR1 (Reaction_protein_degradation) (Curated) (Bmdm_kdo_lipida_atp)
ka(208) = 1;       % 208a: in 1/min Protein degradation of CytALOX5 (Reaction_protein_degradation) (Curated) (Bmdm_kdo_lipida_atp)
                   % 208b: in 1/min Protein degradation of ERMemALOX5 (Reaction_protein_degradation) (Curated) (Bmdm_kdo_lipida_atp)
ka(210) = 1;       % 210a: in 1/min Protein degradation of CytALOX15 (Reaction_protein_degradation) (Curated) (Bmdm_kdo_lipida_atp)
                   % 210b: in 1/min Protein degradation of ERMemALOX15 (Reaction_protein_degradation) (Curated) (Bmdm_kdo_lipida_atp)
ka(215) = 1;       % 215a: in 1/min Protein degradation of ERMemACSL6 (Reaction_protein_degradation) (Curated) (Bmdm_kdo_lipida_atp)
                   % 215b: in 1/min Protein degradation of GolgiMemACSL6 (Reaction_protein_degradation) (Curated) (Bmdm_kdo_lipida_atp)
ka(216) = 1;       % 216a: in 1/min Protein degradation of ERMemACSL5 (Reaction_protein_degradation) (Curated) (Bmdm_kdo_lipida_atp)
                   % 216b: in 1/min Protein degradation of GolgiMemACSL5 (Reaction_protein_degradation) (Curated) (Bmdm_kdo_lipida_atp)
ka(217) = 1;       % 217a: in 1/min Protein degradation of ERMemACSL4 (Reaction_protein_degradation) (Curated) (Bmdm_kdo_lipida_atp)
                   % 217b: in 1/min Protein degradation of GolgiMemACSL4 (Reaction_protein_degradation) (Curated) (Bmdm_kdo_lipida_atp)
ka(218) = 1;       % 218a: in 1/min Protein degradation of ERMemACSL3 (Reaction_protein_degradation) (Curated) (Bmdm_kdo_lipida_atp)
                   % 218b: in 1/min Protein degradation of GolgiMemACSL3 (Reaction_protein_degradation) (Curated) (Bmdm_kdo_lipida_atp)
ka(220) = 1;       % 220a: in 1/min Protein degradation of ERMemACSL1 (Reaction_protein_degradation) (Curated) (Bmdm_kdo_lipida_atp)
                   % 220b: in 1/min Protein degradation of GolgiMemACSL1 (Reaction_protein_degradation) (Curated) (Bmdm_kdo_lipida_atp)
ka(221) = 1;       % 221a: in 1/min Translation of CytTBXAS1_MRNA to generate ERMemTBXAS1 (Reaction_translation) (Curated) (Bmdm_kdo_lipida_atp)
ka(222) = 1;       % 222a: in 1/min Translation of CytPTGS2_MRNA to generate ERMemPTGS2 (Reaction_translation) (Curated) (Bmdm_kdo_lipida_atp)
                   % 222b: in 1/min Translation of CytPTGS2_MRNA to generate ERMemPTGS2BACK (Reaction_translation) (Curated) (Bmdm_kdo_lipida_atp)
                   % 222c: in 1/min Translation of CytPTGS2_MRNA to generate ERMemPTGS2EXPORT (Reaction_translation) (Curated) (Bmdm_kdo_lipida_atp)
                   % 222d: in 1/min Translation of CytPTGS2_MRNA to generate ERMemPTGS2INACT (Reaction_translation) (Curated) (Bmdm_kdo_lipida_atp)
                   % 222e: in 1/min Translation of CytPTGS2_MRNA to generate GolgiMemPTGS2 (Reaction_translation) (Curated) (Bmdm_kdo_lipida_atp)
                   % 222f: in 1/min Translation of CytPTGS2_MRNA to generate GolgiMemPTGS2BACK (Reaction_translation) (Curated) (Bmdm_kdo_lipida_atp)
ka(223) = 1;       % 223a: in 1/min Translation of CytPTGS1_MRNA to generate ERMemPTGS1 (Reaction_translation) (Curated) (Bmdm_kdo_lipida_atp)
ka(226) = 1;       % 226a: in 1/min Translation of CytPTGES2_MRNA to generate GolgiMemPTGES2 (Reaction_translation) (Curated) (Bmdm_kdo_lipida_atp)
ka(228) = 1;       % 228a: in 1/min Translation of CytPTGDS_MRNA to generate ERMemPTGDS (Reaction_translation) (Curated) (Bmdm_kdo_lipida_atp)
                   % 228b: in 1/min Translation of CytPTGDS_MRNA to generate GolgiMemPTGDS (Reaction_translation) (Curated) (Bmdm_kdo_lipida_atp)
ka(229) = 1;       % 229a: in 1/min Translation of CytPLA2G4A_MRNA to generate CytPLA2G4A (Reaction_translation) (Curated) (Bmdm_kdo_lipida_atp)
                   % 229b: in 1/min Translation of CytPLA2G4A_MRNA to generate ERMemPLA2G4A (Reaction_translation) (Curated) (Bmdm_kdo_lipida_atp)
                   % 229c: in 1/min Translation of CytPLA2G4A_MRNA to generate GolgiMemPLA2G4A (Reaction_translation) (Curated) (Bmdm_kdo_lipida_atp)
ka(231) = 1;       % 231a: in 1/min Translation of CytMAN1B1_MRNA to generate GolgiMemMAN1B1 (Reaction_translation) (Curated) (Bmdm_kdo_lipida_atp)
ka(232) = 1;       % 232a: in 1/min Translation of CytLTC4S_MRNA to generate ERMemLTC4S (Reaction_translation) (Curated) (Bmdm_kdo_lipida_atp)
ka(233) = 1;       % 233a: in 1/min Translation of CytLTA4H_MRNA to generate CytLTA4H (Reaction_translation) (Curated) (Bmdm_kdo_lipida_atp)
ka(235) = 1;       % 235a: in 1/min Translation of CytHPGD_MRNA to generate CytHPGD (Reaction_translation) (Curated) (Bmdm_kdo_lipida_atp)
ka(240) = 1;       % 240a: in 1/min Translation of CytGANAB_MRNA to generate ERMemGANAB (Reaction_translation) (Curated) (Bmdm_kdo_lipida_atp)
ka(244) = 1;       % 244a: in 1/min Translation of CytCBR3_MRNA to generate CytCBR3 (Reaction_translation) (Curated) (Bmdm_kdo_lipida_atp)
ka(245) = 1;       % 245a: in 1/min Translation of CytCBR1_MRNA to generate CytCBR1 (Reaction_translation) (Curated) (Bmdm_kdo_lipida_atp)
ka(246) = 1;       % 246a: in 1/min Translation of CytALOX5_MRNA to generate CytALOX5 (Reaction_translation) (Curated) (Bmdm_kdo_lipida_atp)
                   % 246b: in 1/min Translation of CytALOX5_MRNA to generate ERMemALOX5 (Reaction_translation) (Curated) (Bmdm_kdo_lipida_atp)
ka(248) = 1;       % 248a: in 1/min Translation of CytALOX15_MRNA to generate CytALOX15 (Reaction_translation) (Curated) (Bmdm_kdo_lipida_atp)
                   % 248b: in 1/min Translation of CytALOX15_MRNA to generate ERMemALOX15 (Reaction_translation) (Curated) (Bmdm_kdo_lipida_atp)
ka(253) = 1;       % 253a: in 1/min Translation of CytACSL6_MRNA to generate ERMemACSL6 (Reaction_translation) (Curated) (Bmdm_kdo_lipida_atp)
                   % 253b: in 1/min Translation of CytACSL6_MRNA to generate GolgiMemACSL6 (Reaction_translation) (Curated) (Bmdm_kdo_lipida_atp)
ka(254) = 1;       % 254a: in 1/min Translation of CytACSL5_MRNA to generate ERMemACSL5 (Reaction_translation) (Curated) (Bmdm_kdo_lipida_atp)
                   % 254b: in 1/min Translation of CytACSL5_MRNA to generate GolgiMemACSL5 (Reaction_translation) (Curated) (Bmdm_kdo_lipida_atp)
ka(255) = 1;       % 255a: in 1/min Translation of CytACSL4_MRNA to generate ERMemACSL4 (Reaction_translation) (Curated) (Bmdm_kdo_lipida_atp)
                   % 255b: in 1/min Translation of CytACSL4_MRNA to generate GolgiMemACSL4 (Reaction_translation) (Curated) (Bmdm_kdo_lipida_atp)
ka(256) = 1;       % 256a: in 1/min Translation of CytACSL3_MRNA to generate ERMemACSL3 (Reaction_translation) (Curated) (Bmdm_kdo_lipida_atp)
                   % 256b: in 1/min Translation of CytACSL3_MRNA to generate GolgiMemACSL3 (Reaction_translation) (Curated) (Bmdm_kdo_lipida_atp)
ka(258) = 1;       % 258a: in 1/min Translation of CytACSL1_MRNA to generate ERMemACSL1 (Reaction_translation) (Curated) (Bmdm_kdo_lipida_atp)
                   % 258b: in 1/min Translation of CytACSL1_MRNA to generate GolgiMemACSL1 (Reaction_translation) (Curated) (Bmdm_kdo_lipida_atp)

ka_known_parameter_indexes = [ 40 44 45 46 50 52 62 63 64 65 80 88 89 94 96 104 108 183 184 185 188 190 191 193 194 195 197 202 206 207 208 210 215 216 217 218 220 221 222 223 226 228 229 231 232 233 235 240 244 245 246 248 253 254 255 256 258 ];
ka_unkown_parameter_indexes = [ 1 2 3 4 5 6 7 8 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 39 47 53 60 61 66 67 68 69 70 71 72 75 77 78 79 81 82 83 84 85 86 87 90 91 92 93 95 102 103 105 106 107 109 118 119 121 122 123 128 129 130 131 132 134 137 139 140 141 144 145 146 147 149 150 151 152 153 154 159 160 161 162 163 165 168 170 171 172 175 176 177 178 180 181 182 ];

kb = zeros(96,1);
kb(29) = 3.37E-05; % 29a: Km: in mol/l AA ----ACSL1----> AA-COA  at ERMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
                   % 29b: Km: in mol/l AA ----ACSL1----> AA-COA  at GolgiMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
kb(30) = 3.37E-05; % 30a: Km: in mol/l AA ----ACSL2----> AA-COA  at ERMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
                   % 30b: Km: in mol/l AA ----ACSL2----> AA-COA  at GolgiMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
kb(31) = 3.37E-05; % 31a: Km: in mol/l AA ----ACSL3----> AA-COA  at ERMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
                   % 31b: Km: in mol/l AA ----ACSL3----> AA-COA  at GolgiMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
kb(32) = 1.5E-05;  % 32a: Km: in mol/l AA ----ACSL4----> AA-COA  at ERMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
                   % 32b: Km: in mol/l AA ----ACSL4----> AA-COA  at GolgiMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
kb(33) = 3.37E-05; % 33a: Km: in mol/l AA ----ACSL5----> AA-COA  at ERMem  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 33b: Km: in mol/l AA ----ACSL5----> AA-COA  at GolgiMem  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
kb(34) = 3.37E-05; % 34a: Km: in mol/l AA ----ACSL6----> AA-COA  at ERMem  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 34b: Km: in mol/l AA ----ACSL6----> AA-COA  at GolgiMem  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
kb(35) = 1.5E-05;  % 35a: in mol/l ERMemFA -----(-)-----| ERMemACSL1 (Reaction_competitive_inhibition) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 35b: in mol/l ERMemFA -----(-)-----| ERMemACSL2 (Reaction_competitive_inhibition) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 35c: in mol/l ERMemFA -----(-)-----| ERMemACSL3 (Reaction_competitive_inhibition) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 35d: in mol/l ERMemFA -----(-)-----| ERMemACSL5 (Reaction_competitive_inhibition) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 35e: in mol/l ERMemFA -----(-)-----| ERMemACSL6 (Reaction_competitive_inhibition) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 35f: in mol/l GolgiMemFA -----(-)-----| GolgiMemACSL1 (Reaction_competitive_inhibition) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 35g: in mol/l GolgiMemFA -----(-)-----| GolgiMemACSL2 (Reaction_competitive_inhibition) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 35h: in mol/l GolgiMemFA -----(-)-----| GolgiMemACSL3 (Reaction_competitive_inhibition) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 35i: in mol/l GolgiMemFA -----(-)-----| GolgiMemACSL5 (Reaction_competitive_inhibition) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 35j: in mol/l GolgiMemFA -----(-)-----| GolgiMemACSL6 (Reaction_competitive_inhibition) (Assumed) (Bmdm_kdo_lipida_atp)
kb(36) = 3.37E-05; % 36a: in mol/l ERMemFA -----(-)-----| ERMemACSL4 (Reaction_competitive_inhibition) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 36b: in mol/l GolgiMemFA -----(-)-----| GolgiMemACSL4 (Reaction_competitive_inhibition) (Assumed) (Bmdm_kdo_lipida_atp)
kb(39) = 0.0045;   % 39a: Km: in mol/l AA ----PTGS1----> PGH2  at ERMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
kb(40) = 0.0051;   % 40a: Km: in mol/l AA ----PTGS2----> PGH2  at ERMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
                   % 40b: Km: in mol/l AA ----PTGS2----> PGH2  at GolgiMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
                   % 40c: Km: in mol/l AA ----PTGS2BACK----> PGH2  at ERMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
                   % 40d: Km: in mol/l AA ----PTGS2BACK----> PGH2  at GolgiMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
                   % 40e: Km: in mol/l AA ----PTGS2EXPORT----> PGH2  at ERMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
                   % 40f: Km: in mol/l AA ----PTGS2EXPORT----> PGH2  at GolgiMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
kb(44) = 0.0004;   % 44a: Km: in mol/l PGH2 ----HPGDS----> PGD2  at ERMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
kb(45) = 0.0001;   % 45a: Km: in mol/l PL ----PLA2G4A----> AA  at ERMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
                   % 45b: Km: in mol/l PL ----PLA2G4A----> AA  at GolgiMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
kb(46) = 1.38E-05; % 46a: Km: in mol/l PGH2 ----PTGDS----> PGD2  at ERMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
                   % 46b: Km: in mol/l PGH2 ----PTGDS----> PGD2  at GolgiMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
kb(47) = 0.0002;   % 47a: Km: in mol/l PGH2 ----PTGES2----> PGE2  at GolgiMem  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
kb(50) = 2E-08;    % 50a: Km: in mol/l PGH2 ----TBXAS1----> TXA2  at ERMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
kb(52) = 0.0003;   % 52a: Km: in mol/l PGE2 ----CBR1----> PGF2ALPHA  in Cyt  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
kb(53) = 0.0003;   % 53a: Km: in mol/l PGE2 ----CBR3----> PGF2ALPHA  in Cyt  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
kb(60) = 0.008;    % 60a: in mol/l CytPGD2 -----(-)-----| CytHPGD (Reaction_competitive_inhibition) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 60b: Km: in mol/l PGD2 ----HPGD----> 13,14-DIHYDRO-15-KETO-PGD2  in Cyt  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
kb(61) = 0.0003;   % 61a: in mol/l CytPGE2 -----(-)-----| CytHPGD (Reaction_competitive_inhibition) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 61b: Km: in mol/l PGE2 ----HPGD----> 13,14-DIHYDRO-15-KETO-PGE2  in Cyt  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
kb(62) = 5E-05;    % 62a: in mol/l CytPGF2ALPHA -----(-)-----| CytHPGD (Reaction_competitive_inhibition) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 62b: Km: in mol/l PGF2ALPHA ----HPGD----> 13,14-DIHYDRO-15-KETO-PGF2ALPHA  in Cyt  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
kb(63) = 7E-05;    % 63a: in mol/l CytPGJ2 -----(-)-----| CytHPGD (Reaction_competitive_inhibition) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 63b: Km: in mol/l PGJ2 ----HPGD----> 13,14-DIHYDRO-15-KETO-PGJ2  in Cyt  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
kb(64) = 2.3E-05;  % 64a: Km: in mol/l LTA4 ----LTA4H----> LTB4  in Cyt  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
kb(65) = 2E-05;    % 65a: Km: in mol/l LTA4 ----LTC4S----> LTC4  at ERMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
kb(66) = 4E-05;    % 66a: Km: in mol/l PTGS2 ----GANAB----> PTGS2EXPORT  at ERMem  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 66b: Km: in mol/l PTGS2 ----MOGS----> PTGS2EXPORT  at ERMem  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
kb(68) = 8E-05;    % 68a: Km: in mol/l PTGS2 ----MAN1B1----> PTGS2BACK  at GolgiMem  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
kb(88) = 4E-05;    % 88a: in mol/l ERMemAA -----(-)-----| ERMemALOX5 (Reaction_competitive_inhibition) (Curated) (Bmdm_kdo_lipida_atp)
                   % 88b: Km: in mol/l AA ----ALOX5----> 5HPETE  at ERMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)
kb(89) = 1E-06;    % 89a: in mol/l ERMem5HPETE -----(-)-----| ERMemALOX5 (Reaction_competitive_inhibition) (Assumed) (Bmdm_kdo_lipida_atp)
                   % 89b: Km: in mol/l 5HPETE ----ALOX5----> LTA4  at ERMem  (Reaction_michaelis_menton) (Assumed) (Bmdm_kdo_lipida_atp)
kb(96) = 5E-05;    % 96a: Km: in mol/l AA ----ALOX15----> 15-HETE  at ERMem  (Reaction_michaelis_menton) (Curated) (Bmdm_kdo_lipida_atp)

kb_known_parameter_indexes = [ 29 30 31 32 39 40 44 45 46 50 52 64 65 88 96 ];
kb_unkown_parameter_indexes = [ 33 34 35 36 47 53 60 61 62 63 66 68 89 ];

